# for setting up docker-compose, see https://www.docker.com/blog/containerized-python-development-part-2/

version: "3.7"

services:
  nbk:
    build:
      context: .
    volumes:
      - ./src:/app
    ports:
      - "8888:8888"
    command:
      [jupyter-lab, --no-browser, --ip=0.0.0.0, --allow-root, --port=8888]
  app:
    build:
      context: .
    volumes:
      - ./src:/app
    ports:
      - "9999:9999"
    stdin_open: true
    tty: true
    command: [python, app.py]
